<?php

namespace Piwi\S2p\PhotoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PhotoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PhotoRepository extends EntityRepository
{
    public function findLatestPhotos($limit = 10)
    {
        $qb = $this->createQueryBuilder('photo');

        $qb->orderBy('photo.date', 'ASC');
        $qb->setMaxResults($limit);

        return $qb->getQuery()->getResult();
    }
}
