piwi_s2p_user_admin_list:
    pattern:  /list
    defaults: { _controller: PiwiS2pUserBundle:Admin:list }

piwi_s2p_user_admin_edit:
    pattern:  /{username}/edit
    defaults: { _controller: PiwiS2pUserBundle:Admin:edit }

piwi_s2p_user_admin_delete:
    pattern:  /{username}/delete
    defaults: { _controller: PiwiS2pUserBundle:Admin:delete }