parameters:
    piwi_system_mail.mailer.class: Piwi\System\MailBundle\Services\Mailer

services:
    piwi_system_mail.mailer:
        class: %piwi_system_mail.mailer.class%
        arguments:
            - @doctrine
            - @mailer