# HWIO Oauth Bundle
hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect

# Homepage
homepage:
    pattern:  /
    defaults: { _controller: PiwiS2pDashboardBundle:Default:index }

# S2p app
piwi_s2p_dashboard:
    resource: "@PiwiS2pDashboardBundle/Resources/config/routing.yml"
    prefix:   /dashboard

piwi_s2p_user:
    resource: "@PiwiS2pUserBundle/Resources/config/routing.yml"
    prefix:   /profile

# System
piwi_system_user:
    resource: "@PiwiSystemUserBundle/Resources/config/routing.yml"
    prefix:   /

# App
