security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_MEMBER:      ROLE_USER
        ROLE_ADMIN:       ROLE_MEMBER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                login_path: /login
                check_path: /login_check
                use_referer: true
                remember_me: true
            oauth:
                resource_owners:
                    facebook: /connect/check-facebook
                login_path: /login
                failure_path: /login/failed
                use_referer: true
                default_target_path: /
                remember_me: true
                oauth_user_provider:
                    #this is my custom user provider, created from FOSUBUserProvider - will manage the
                    #automatic user registration on your site, with data from the provider (facebook. google, etc.)
                    service: piwi_user_provider
            logout:       true
            anonymous:    true
            remember_me:
                key: "%secret%"
                always_remember_me: true
                lifetime: 31536000 # 365 days in seconds
                path: /
                domain: ~ # Defaults to the current domain from $_SERVER

        login:
            pattern:  ^/login$
            security: false

            remember_me:
                key: "%secret%"
                always_remember_me: true
                lifetime: 31536000 # 365 days in seconds
                path: /
                domain: ~ # Defaults to the current domain from $_SERVER

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user/[a-zA-Z0-9]+/.*, role: IS_AUTHENTICATED_FULLY }
        - { path: ^/photo/add/.*, role: ROLE_MEMBER }
        - { path: ^/events/add, role: ROLE_MEMBER }
        - { path: ^/admin/, role: ROLE_ADMIN }