parameters:
#    piwi_dst_core.example.class: Piwi\Dst\CoreBundle\Example

services:
#    piwi_dst_core.example:
#        class: %piwi_dst_core.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
