<?php

namespace Piwi\S2p\EventBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EventAttendeeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventAttendeeRepository extends EntityRepository
{
}
