<?php

namespace Piwi\S2p\CommentBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EventAttendeeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends EntityRepository
{
    public function findLatestComments($limit = 10)
    {
        $qb = $this->createQueryBuilder('comment');

        $qb->orderBy('comment.createdAt', 'DESC');
        $qb->setMaxResults($limit);

        return $qb->getQuery()->getResult();
    }
}
