piwi_s2p_photo_photo_index:
    pattern:  /
    defaults: { _controller: PiwiS2pPhotoBundle:Photo:index }

piwi_s2p_photo_photo_add:
    pattern:  /add/step1
    defaults: { _controller: PiwiS2pPhotoBundle:Photo:step1 }

piwi_s2p_photo_photo_add_step2:
    pattern:  /add/step2
    defaults: { _controller: PiwiS2pPhotoBundle:Photo:step2 }

piwi_s2p_photo_photo_add_step3:
    pattern:  /add/step3
    defaults: { _controller: PiwiS2pPhotoBundle:Photo:step3 }

piwi_s2p_photo_photo_album:
    pattern:  /{slug}
    defaults: { _controller: PiwiS2pPhotoBundle:Photo:album }

piwi_s2p_photo_photo_edit:
    pattern:  /edit/{slug}
    defaults: { _controller: PiwiS2pPhotoBundle:Photo:edit }

piwi_s2p_photo_photo_delete:
    pattern:  /delete/{slug}
    defaults: { _controller: PiwiS2pPhotoBundle:Photo:delete }

piwi_s2p_photo_photo_delete_photo:
    pattern:  /delete/photo/{id}
    defaults: { _controller: PiwiS2pPhotoBundle:Photo:deletePhoto }

piwi_s2p_photo_photo_select_preview:
    pattern:  /{slug}/preview/{id}
    defaults: { _controller: PiwiS2pPhotoBundle:Photo:selectPreview }