parameters:
    piwi_user_provider.class: Piwi\System\UserBundle\Security\Core\User\FOSUBUserProvider
    piwi_system_user.manager.class: Piwi\System\UserBundle\Doctrine\UserManager
 
services:
    piwi_user_provider:
        class: "%piwi_user_provider.class%"
        #this is the place where the properties are passed to the UserProvider - see config.yml
        arguments: [ @liip_imagine.cache.manager, @knp_gaufrette.filesystem_map, @fos_user.user_manager, { facebook: facebookId } ]

    piwi_user.loginlistener:
        class: Piwi\System\UserBundle\EventListener\LoginListener
        arguments: [@security.context, @router]
        tags:
            - { name: kernel.event_listener, event: security.authentication.success, method: handle }
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }

    piwi_system_user.manager:
        class: %piwi_system_user.manager.class%
        arguments:
            - @security.encoder_factory
            - @fos_user.util.username_canonicalizer
            - @fos_user.util.email_canonicalizer
            - @fos_user.entity_manager
            - %fos_user.model.user.class%